### ISSUE TITLE
sometimes the PPP also sometimes just doesn't want to boot (possibly it is not sure)

### ISSUE THREAD

**Issue by ghost** [Daniel-Abrecht/dpa-image-builder#3]
~~in config/default/config~~

~~config change to:~~
~~DISTRO = debian~~
~~BUILD_PACKAGES = yes~~
~~USE_IMAGE_BUILDER_REPO = no~~
~~DONT_BUILD_IF_IN_REPO = no~~

~~build with:~~
~~make BOARD=pinephone-pro~~

~~--~~

~~black screen, no boot~~

the first problem is caused by the pinephone-pro and not by this project.

**Comment by ghost** [comment]
If it can help you, I will upload several files of the result:

(image) dpa-image-builder/bin/:
https://ufile.io/f56gtxzs

(kernel) dpa-image-builder/kernel/bin/:
https://ufile.io/f/5g38z

(u-boot) dpa-image-builder/platform/pinephone-pro/uboot/bin/:
https://ufile.io/f/4slji

(various) dpa-image-builder/build/bin/:
https://ufile.io/f/91fcz

**Comment by Daniel-Abrecht** [comment]
Thanks for reporting this issue. Unfortunately, I wasn't able to reproduce it. I tried the image you linked to, and it did boot on my device.
There can be many reasons for that. For example, maybe the SD card was bad. Or if you have installed Tow-Boot, I haven't tested yet if this image works with that (but I plan to look into it). In my experience, sometimes the PPP also sometimes just doesn't want to boot, I then need to try a few times (I should probably also look into that at some point).

However, I did notice another thing I'll have to look into. It seams the touchscreen didn't work in the initramfs stage, so that's another thing I'll have to look into.

**Comment by ghost** [comment]
No problem, I really like the work you do!
i find it amazing that you were able to boot the iso because I tested with 3 different sd cards (kingstone, samsung and a chinese one), with dd or balenaetcher and nothing worked. I don't use an alternative bootloader.
Could I know the sd card and the installation method you used?
and good luck to you for the continuation !

**Comment by Daniel-Abrecht** [comment]
I'm using pv to write the image to the sd card. The sd card I'm using is just a regular SanDisk Ultra 32GB card.

![20220511_211051](https://user-images.githubusercontent.com/10375108/167933885-afa4589b-7154-4fe6-9c9a-0c6ae058912c.jpg)
https://user-images.githubusercontent.com/10375108/167934134-08b34e45-6460-4b58-a2e6-0714e7fcaed9.mp4
https://user-images.githubusercontent.com/10375108/167937817-ebf106d0-b62b-4d19-bedd-d1e390b58631.mp4

**Comment by ghost** [comment]
ow thank you that's really nice of you! <3
you are really a very nice person besides doing a great job! <3

I am currently testing this !

**Comment by ghost** [comment]
after plugging in my pinephone-pro and pressing the start button at the same time, it started working again for no reason.

I thought it was a battery charging problem, since I'm using an external dock, but no,
I hope one day we can charge the pinephonepro even when it's turned off because this is really a problem,

i started to believe that your repo was magic xD

for the fact that the image is not always started, I will do some tests during the next month by redeveloping my lite version of your project and I will let you know if I face this kind of problem. in order to make me a new opinion because all the old tests I did can be deceived by this battery error, I will keep you informed hoping to be useful!

Thanks a lot for your help :3

**Comment by ghost** [comment]
i've been doing a lot of testing over the last three days, and i've found that when the phone doesn't boot up, all you have to do is plug in the charging cable (without necessarily removing and reconnecting the battery) and simply press the power button for the phone to restart without any further action, the boot-glitch is probably due to a problem somewhere with the power management.

obviously the pinephone-pro has problems with its power management
